### ISSUE TITLE
2-sql-internals nestahovat dataset ak uz existuje

### ISSUE THREAD

**Issue by FilipVozar** [fiit-pdt/hands-on#2]
Ked sa nastartuje stopnuty (nie vymazany) kontajner, tak stahuje znova dataset http://otvorenezmluvy.sk/data/otvorenezmluvy_dump_2013-09-08.sql.gz aj ked uz existuje. Kedze je relativne velky tak by mozno bolo dobre do entrypointu dat check a nestahovat ho znovu ak uz existuje.

**Comment by kremso** [comment]
Pustas ho takto?

`docker run -v ~/pg-l-data:/var/lib/postgresql/data -p 5432:5432 fiitpdt/postgres-l`

**Comment by FilipVozar** [comment]
vsimol som si ze ten check tam uz je, ale moj pripad nepokryl. Vyfailovalo mi to medzi extrahovanim datasetu a spustenim postgresu (na /var/lib/postgresql/data som omylom mountol adresar, ktory uz mal v sebe nejake subory, tak sa postgres odmietol nastartovat), takze postgres este nevytvoril ten subor, ktoreho existencia sa checkuje v entrypointe (inak nie je tam tiez bug? nema to byt $PGDATA/$PG_VERSION namiesto $PGDATA/PG_VERSION?)

**Comment by kremso** [comment]
Chapem co sa stalo, ale poviem ti pravdu ze tento edge case nebudem riesit.
